name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: |
          docker build . -t july
          docker run --name july --env CXX=clang++-13 -v $PWD:/project -d july
      - name: Build Cmake
        run: |
          docker exec july mkdir -p /project/build
          docker exec -w /project/build july cmake ..
          docker exec -w /project/build cmake --build .
      - name: Google Tests
        run: docker exec -w /project/build/test ./julytest
