name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: docker build . -t july
      - name: Build Cmake
        run: |
          docker run --name july --env CXX=clang++-17 -v $PWD:/project -d july
          docker exec july \
            mkdir -p project/build && \
            cd project/build && \
            cmake .. && \
            cmake --build .
