name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: |
          docker build . -t july
          docker run --name july --env CXX=clang++-13 -v $PWD:/project -d july
          docker exec -d july mkdir -p project/build
          docker exec -d july cd project/build
          docker exec -d july cmake ..
          docker exec -d july cmake --build .