name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  docker-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker
        run: docker build . -t july

  cmake-build:
    needs: docker-build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build Cmake
        run: |
          docker run --name july --env CXX=clang++-13 -v $PWD:/project -d july
          docker exec -d july mkdir -p project/build
          docker exec -d july cd project/build
          docker exec -d july cmake ..
          docker exec -d july cmake --build .
