name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . -t july
      - name: Run the Docker image
        run: docker run --name july --env CXX=clang++-13 -v $PWD:/project -d july

  run:

    runs-on: ubuntu-latest

    container:
      image: july
      
    steps:
      - name: Build the project
        run: |
          mkdir -p project/build
          cmake ..
          cmake --build .